<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DisplayToolkit.Automation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DisplayToolkit.Core\DisplayToolkit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DisplayToolkit.Automation.Tests" />
  </ItemGroup>

</Project>
